
GUI = False
DEV_MODE = False
DELAY = 1000
STEP_LENGTH = 0.1
DESIRED_UNITS_OF_SIMULATION = 7200
TOTAL_UNITS_OF_SIMULATION = int(DESIRED_UNITS_OF_SIMULATION / STEP_LENGTH) if DEV_MODE else DESIRED_UNITS_OF_SIMULATION
HIDDEN_LAYER_SIZES = [
    64,
    # 128,
    # 256,
    # 512,
    # 1024
    ]
EPISODES = 500
