
GUI: bool = False
DEV_MODE: bool = False
DELAY: int = 1000
STEP_LENGTH: float = 0.1
DESIRED_UNITS_OF_SIMULATION: int = 7200
TOTAL_UNITS_OF_SIMULATION: int = int(DESIRED_UNITS_OF_SIMULATION / STEP_LENGTH) if DEV_MODE else DESIRED_UNITS_OF_SIMULATION
HIDDEN_LAYER_SIZES: list[int] = [
    64,
    # 128,
    # 256,
    # 512,
    # 1024
    ]
EPISODES: int = 500
